apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-app
spec:

  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort